name: CI/CD - Flutter App

on:
  push:
    branches:
      - master  # Or your default branch


jobs:
  build-deploy-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.16.9'
        
    - name: Install dependencies
      run: flutter pub get
      
    # Build web app
    - name: Build Web (Canvaskit Renderer)
      run: flutter build web --web-renderer canvaskit
    
    # Build APK for Android
    - name: Build APK
      run: flutter build apk
    
    # Upload APK to GitHub Releases
    - name: Upload APK to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/app/outputs/flutter-apk/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
